services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./backend/uploads/produtos:/usr/share/nginx/html/images/produtos:ro
      - ./backend/api/estoque:/usr/share/nginx/html/images/estoque:ro
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: tech_store
      DB_USER: techstore
      DB_PASSWORD: techstore
    volumes:
      - ./backend:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: tech_store
      MYSQL_USER: techstore
      MYSQL_PASSWORD: techstore
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data:
